### ISSUE TITLE
sub Redis.Remove not removing when PID has different lengths

### ISSUE THREAD

**Issue by tvatavuk** [davidjrh/dnn.rediscachingprovider#10]
PID is used for InstanceUniqueId.

ProcessMessage can't remove cache key when PID has different string length as in this test.

![dnn rediscachingprovider-2016-02-01 10_32_29-task manager](https://cloud.githubusercontent.com/assets/2724850/12714647/38df2c08-c8d6-11e5-9ce5-08d4b4549226.png)

**Comment by davidjrh** [comment]
Good catch! Also noticed that if we have the same process ID on different machines, the cache item would not be removed. I have added the machine name to the InstanceUniqueId as well.
