### ISSUE TITLE
Shared.GetProviderConfigAttribute failed for RedisOutputCachingProvider

### ISSUE THREAD

**Issue by evgeniy-polyakov** [davidjrh/dnn.rediscachingprovider#12]
Shared.GetProviderConfigAttribute gets the provider using the following code:
`var provider = Config.GetProvider("caching", providerName);`.
Here `caching` is name of the section in web.config where `providerName` is defined.
RedisOutputCachingProvider is defined in `outputCaching` section, and the method can not get the provider.
As a result RedisOutputCachingProvider always uses default values of `useCompression`, `keyPrefix`, `silentMode`.

**Comment by davidjrh** [comment]
Good catch, I will add the fix on the next release

**Comment by davidjrh** [comment]
Fixed on https://github.com/davidjrh/dnn.rediscachingprovider/commit/1fe73e0d1ff9e3dea78ec2f7de440ea380c4cc17
