### ISSUE TITLE
Remove cache incorrectly

### ISSUE THREAD

**Issue by krurkrit** [davidjrh/dnn.rediscachingprovider#16]
Hi David,

I found RedisCachingProvider remove cache incorrectly when run on multiple instances, number of digit of process ID are different.

Please see File RedisCachingProvider.cs, Line 75
instance.Remove(redisValue.ToString().Substring(InstanceUniqueId.Length + 1), false);

ex. Process ID of instance 1 is 9999, but Process ID of instance 2 is 12345 -- Instance 1 publish message 'HOSTGUID_DNN_Process_9999_RemoveKey'

In Instance 2
HOSTGUID_DNN_Process_9999_RemoveKey -- Publish message
HOSTGUID_DNN_Process_12345 -- Instance unique ID

so, Removing key will be 'emoveKey'

Please see code on my repository, I changed it to separate by colon (:), same as clear key message. I also changed it to support key with colon.

https://github.com/krurkrit/dnn.rediscachingprovider/blob/master/Release/RedisCachingProvider_01.00.04_Source/RedisCachingProvider/RedisCachingProvider.cs

**Comment by evgeniy-polyakov** [comment]
As far as I know this is already fixed. Current process id is hexadecimal with padding 0 if length is less then 8. See [RedisCachingProvider.cs#96](https://github.com/davidjrh/dnn.rediscachingprovider/blob/master/RedisCachingProvider/RedisCachingProvider.cs#L96).
So your instance ids should be the following:
`HOSTGUID_DNN_Process_00009999`
`HOSTGUID_DNN_Process_00012345`

**Comment by krurkrit** [comment]
I would like to reissue about this issue. Because InstanceUniqueId contains Environment.MachineName

So, First machine name is "Primary", Another machine is "Secondary"
the instance on "Primary" will publish message "HOSTGUID_Primary_00009999_RemoveKey"

In the another instance on "Secondary"
HOSTGUID_Primary_00009999_RemoveKey -- Publish message
HOSTGUID_Secondary_00012345 -- Instance unique ID

so, Removing key will be 'moveKey'

Could you please use a separator (ex. ':') to separate unique id and remove key?

**Comment by davidjrh** [comment]
I have accepted this pull request that fixes the issue https://github.com/davidjrh/dnn.rediscachingprovider/commit/1fc5b4a91c6444ead4f4b634f5243717974a2bfc
