### ISSUE TITLE
Why rediscachingprovider does not pub/sub for inserting

### ISSUE THREAD

**Issue by krurkrit** [davidjrh/dnn.rediscachingprovider#19]
Hi David,

Why rediscachingprovider does not pub/sub when key is inserted?

Such as we have 2 instances, if instance 1 insert key1, should publish message to another instance?
I try to pub/sub for inserting but I found performance issue (I have around 50-100 websites on a DNN server).

Do you have any idea?

PS: I suggest to improve performance for pub/sub for deleting/clearing. I found it has problem when create DNN website with the large template file.

**Comment by davidjrh** [comment]
When debugging I have seen that there are a lot of calls to clear cache, and refreshing settings in a single transaction. If we add extra work between those calls (i.e. imagine we have 20 webservers), we would be adding more overhead and getting worst performance than just use lazy loading (clear the cache and reload when used the first time).

**Comment by davidjrh** [comment]
Going to close this issue. If anybody wants to add more suggestions, please re-open it
