### ISSUE TITLE
The configuration is read only error

### ISSUE THREAD

**Issue by samtech09** [davidjrh/dnn.rediscachingprovider#25]
DNN: 9.0.2
Redis : 2.8.17 (Debian Linux)

Redis sever is being used with few other applications and is working well.
Issues:
1. Can not change configuration from DNN GUI ((Settings -> Redis Caching). Update button hilighted but do not work (no visual indication and also web.config not updated)

2. If we change silentMode in we.config from 'true' to'false' we get following error

[ConfigurationErrorsException: The configuration is read only.]
   System.Configuration.ConfigurationElement.SetPropertyValue(ConfigurationProperty prop, Object value, Boolean ignoreLocks) +842647
   DotNetNuke.Providers.RedisCachingProvider.Shared.get_ConnectionString() +261
   DotNetNuke.Providers.RedisCachingProvider.<>c.<.cctor>b__22_0() +27
   System.Lazy`1.CreateValue() +455
   System.Lazy`1.get_Value() +14277602
   DotNetNuke.Providers.RedisCachingProvider.RedisCachingProvider.get_RedisCache() +64
   DotNetNuke.Providers.RedisCachingProvider.RedisCachingProvider.GetItem(String key) +881
   DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromRuntimeCache(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired) +68
   DotNetNuke.Common.Utilities.DataCache.GetCachedData(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired, Boolean storeInDictionary) +31
   DotNetNuke.Services.Log.EventLog.DBLoggingProvider.GetLogTypeInfo() +190
   DotNetNuke.Services.Log.EventLog.LogController.GetLogTypeInfoDictionary() +119
   DotNetNuke.Services.Log.EventLog.LogController.AddLog(LogInfo logInfo) +606

**Comment by davidjrh** [comment]
I found the error and will create a patch. Meanwhile, add this to the connection string ",abortconnect=false"

**Comment by davidjrh** [comment]
I have fixed the issue on https://github.com/davidjrh/dnn.rediscachingprovider/commit/4086c6a0aee2fd3955ab45976c8e282f99104fb0 and released a new version 3.0.1, since this was a showstopper https://github.com/davidjrh/dnn.rediscachingprovider/releases/tag/v3.0.1
