### ISSUE TITLE
DNN not using RedisCaching at all

### ISSUE THREAD

**Issue by samtech09** [davidjrh/dnn.rediscachingprovider#26]
Here is my config for local test deployment
```
<connectionStrings>
<add name="RedisCachingProvider" connectionString="192.168.60.206" providerName="DotNetNuke.Providers.RedisCachingProvider" />
...
</connectionStrings>


<appSettings>
    <add key="redis-port" value="6379" />
    <add key="redis-host" value="192.168.60.206" />
</appSettings>


<caching defaultProvider="RedisCachingProvider">
      <providers>
        <clear />
        <add name="RedisCachingProvider" type="DotNetNuke.Providers.RedisCachingProvider.RedisCachingProvider, DotNetNuke.Providers.RedisCachingProvider" providerPath="~\Providers\CachingProviders\RedisCachingProvider\" useCompression="false" silentMode="false" keyPrefix="dnn9-" />
        ...
</caching>


<outputCaching defaultProvider="RedisOutputCachingProvider">
      <providers>
        <clear />
        ...
        <add name="RedisOutputCachingProvider" type="DotNetNuke.Providers.RedisCachingProvider.RedisOutputCachingProvider, DotNetNuke.Providers.RedisCachingProvider" providerPath="~\Providers\CachingProviders\RedisCachingProvider\" useCompression="false" silentMode="true" />
      </providers>
    </outputCaching>
```

As i set key-prefix it set to 'dnn9-', but after running portal i am not able to see any key beginning with that prefix in redis-server. Even no keys with DNN GUID.
It looks DNN is not using RedisCaching at all.

Redis server is accessible from DNN server, as i confirmed with telnet.

**Comment by davidjrh** [comment]
Hi @samtech09, your configuration looks good to me. Can you check the log4net logs under \portals\_default\logs for any clue? 

PS: those appSettings with the port, host, etc. are not used (did you added them manually?). If you want to specify a different port or any other option, you must do it on the connection string. For the different options check https://stackexchange.github.io/StackExchange.Redis/Configuration

**Comment by davidjrh** [comment]
Hi, I think your issue is related to https://github.com/davidjrh/dnn.rediscachingprovider/issues/25. Can you test the workaround?

**Comment by davidjrh** [comment]
Fixed on https://github.com/davidjrh/dnn.rediscachingprovider/releases/tag/v3.0.1
