### ISSUE TITLE
Page level changes not propagating via Redis?

### ISSUE THREAD

**Issue by weschang** [davidjrh/dnn.rediscachingprovider#33]
I'm using two IIS server web farm setup, running DNN 9.3.1 (community edition) and latest DNN Redis Provider (v3.1) with Azure Redis Cache (Standard C1).

When I make module level changes, such as adding HTML module, updating HTML content, the changes propagate from one VM to another.

However, if I add a page and update page permissions, such changes do not propagate between VMs. 

Any idea why this is happening? Any DNN settings that I might need to tweak?

Thanks,
Wesley

**Comment by weschang** [comment]
@davidjrh does this DNN Redis provider requires a load balancer on top of the VMs in order for changes to propagate between servers correctly?

**Comment by weschang** [comment]
Turns out this is a connectivity issue: the test site is not able to connect to Azure Redis Cache because Azure Redis requires TLS 1.2, and the test was running .NET framework 4.5. Once we changed to .NET 4.6, every works as intended.

**Comment by davidjrh** [comment]
Understood. If you are in a similar scenario and upgrading .net Framework is not possible, drop this assembly on the \bin folder to force TLS 1.2 on all outbound connections.

https://github.com/davidjrh/dnn.tls12
