### ISSUE TITLE
Unserializable classes

### ISSUE THREAD

**Issue by ggiordan** [davidjrh/dnn.rediscachingprovider#4]
based on my testing with DNN 7.4.1, there are several issues with classes that are not serializable.
The announcements and gallery modules both throw errors (I'm submitted a pull request for the announcements module)
There is another in the core:
Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Type 'DotNetNuke.Common.Utilities.UrlTrackingInfo' in Assembly 'DotNetNuke, Version=7.4.0.353, Culture=neutral, PublicKeyToken=null' is not marked as serializable. ---> System.Runtime.Serialization.SerializationException: Type 'DotNetNuke.Common.Utilities.UrlTrackingInfo' in Assembly 'DotNetNuke, Version=7.4.0.353, Culture=neutral, PublicKeyToken=null' is not marked as serializable. at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type) at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context) at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo() at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Type objectType, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, SerializationBinder binder) at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo) at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck) at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck) at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph) at DotNetNuke.Providers.RedisCachingProvider.RedisCachingProvider.Serialize(Object source) in e:\PageConfirmDnn\PageConfirmDnn\Providers\CachingProviders\RedisCachingProvider\RedisCachingProvider.cs:line 295 at DotNetNuke.Providers.RedisCachingProvider.RedisCachingProvider.Insert(String key, Object value, DNNCacheDependency dependency, DateTime absoluteExpiration, TimeSpan slidingExpiration, CacheItemPriority priority, CacheItemRemovedCallback onRemoveCallback) in e:\PageConfirmDnn\PageConfirmDnn\Providers\CachingProviders\RedisCachingProvider\RedisCachingProvider.cs:line 168 at DotNetNuke.Common.Utilities.DataCache.SetCache(String CacheKey, Object objObject, DNNCacheDependency objDependency, DateTime AbsoluteExpiration, TimeSpan SlidingExpiration, CacheItemPriority Priority, CacheItemRemovedCallback OnRemoveCallback) at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromRuntimeCache(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired) at DotNetNuke.Common.Utilities.DataCache.GetCachedData[TObject](CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired, Boolean storeInDictionary) at DotNetNuke.Data.RepositoryBase`1.GetById[TProperty,TScopeType](TProperty id, TScopeType scopeValue) at DotNetNuke.Modules.Announcements.Components.Business.AnnouncementsController.GetAnnouncement(Int32 itemID, Int32 moduleID) at DotNetNuke.Modules.Announcements.MVP.Presenters.AnnouncementsEditPresenter.GetAnnouncement(Object sender, EventArgs e) at DotNetNuke.Modules.Announcements.AnnouncementsEdit.OnLoad(EventArgs e) --- End of inner exception stack trace ---

**Comment by davidjrh** [comment]
I have created an issue for the Core fix. We can track it at https://dnntracker.atlassian.net/browse/DNN-7671
I'm going to close the issue here since they are not Redis caching provider related (must be fixed on other projects). 

Thanks!

**Comment by ggiordan** [comment]
works for me.  thanks!

any thoughts on a change that allow either a fallback or cache bypass when this happens?
basically, degrade gracefully and log the error.  Just thinking this probably isn't the only non-serializable objects.  I'm using the redis provider @ rackspace, the performance is SUPER.  Thanks so much for the implementation!

**Comment by davidjrh** [comment]
As the provider works in hybrid mode (storing cache in memory and in Redis), the cached object would be in memory as well. To silently fail on errors and log the exception, use the silentMode="true" attribute on the provider configuration at the web.config. The attribute was created as a workaround to solve this type of issue.

**Comment by ggiordan** [comment]
Fair enough and agreed.
In a way, I was thinking outloud.

I'm sure we will be playing whack-a-mole with this for some time.

I see that Joe updated the defect... I suspect that 7.4.2 may be too far down the pipe (I REALLY NEED the update, there are so many broken things in 7.4.0...)  for this fix to make it.

**Comment by davidjrh** [comment]
Yeah, too late for 7.4.2, that was released 3 days ago http://dotnetnuke.codeplex.com/releases/view/617762

We usually use https://dnndummycaching.codeplex.com/ to detect them while on development, so shouldn't be too many of them passing the unit tests. If you find any, please create a JIRA issue. Remember that you can create your own fix if it's urgent by rebuilding the DNN core library while waiting for the fixed release.
